name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Verify project structure
      run: |
        echo "📁 Project structure:"
        ls -la
        echo "📦 Package files:"
        ls -la package*.json
        echo "🔧 Build config:"
        ls -la vite.config.ts firebase.json
        
    - name: Install dependencies
      run: |
        echo "📥 Installing dependencies..."
        npm ci --verbose
        
    - name: TypeScript check
      run: |
        echo "🔍 Running TypeScript check..."
        npx tsc --noEmit
        
    - name: Build project
      run: |
        echo "🏗️ Building project..."
        npm run build
        
    - name: Verify build output
      run: |
        echo "✅ Verifying build output..."
        if [ ! -d "dist" ]; then
          echo "❌ Build output directory 'dist' not found"
          exit 1
        fi
        
        echo "📁 Build output contents:"
        ls -la dist/
        
        if [ ! -f "dist/index.html" ]; then
          echo "❌ index.html not found in build output"
          exit 1
        fi
        
        echo "✅ Build verification successful"
        
    - name: Configure Node.js for deployment
      run: |
        echo "🔧 Configuring Node.js to prevent memory leaks..."
        echo "NODE_OPTIONS=--max-old-space-size=4096 --max-listeners=20" >> $GITHUB_ENV
        
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
